import type { Metadata } from "next";
import "@/styles/globals.css";
import { Inter } from "next/font/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin", "cyrillic"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${inter.className} px-4 sm:px-6 md:px-8`}>{children}</body>
    </html>
  );
}
